### ISSUE TITLE
Cannot start a query

### ISSUE THREAD

**Issue by BenjaminSchumann** [noorjax/Chat-GPT-Data-Analyst#1]
Hi @noorjax ,

followed your steps from your [blog post](https://www.anylogic.com/blog/use-chatgpt-for-data-analysis-make-your-anylogic-model-talk/). However, upon running a model, I get this error: 
<img width="871" alt="image" src="https://github.com/noorjax/Chat-GPT-Data-Analyst/assets/16608112/96ab552a-9c99-41bf-bc85-b5ca288c4f96">

This is what I did:
- install fresh Anaconda (did not change any default settings, the python.exe sits in the correct path)
- followed your steps from your [blog post](https://www.anylogic.com/blog/use-chatgpt-for-data-analysis-make-your-anylogic-model-talk/)
- drag in your `Chat` block and setup as per the steps, with my own API and assistant key, of course
- also tried dragging in the `Py Connector` block next to the `Chat` block, same result

Is there something I am missing? Do I need to setup some Anaconda stuff? Do I need to do something with the "Pypeline" library at all? (your tutorial does not mention anything except to add it to AnyLogic)

Any pointers greatly appreciated :)

**Comment by noorjax** [comment]
Make sure you have Python installed in your machine, and install the
following libraries in your python environment: python-dotenv & openai.

**Comment by BenjaminSchumann** [comment]
Thx, I didn't have the `openai` package installed by default, thx
